#pragma once
#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
#include <string>
#include <locale>
#include <stdlib.h> 
#include <cwchar>
#include <iomanip>
#include <stdio.h>
#include <tchar.h>
#include <fstream>
#include <ctime>
#include <string.h>
#include <mbstring.h>
#include "In.h"
#include "Error.h"
#include "Parm.h"
#include "Log.h"
#include "Out.h"
#include "Graphs.h"
#include "FST.h"
#include "IT.h"
#include "LT.h"
#include "LexAnalysis.h"
using namespace std;